[workspace]
members = ["server", "fixtures"]
resolver = "2"

[workspace.dependencies]
reqwest = { version = "0.12.20", features = [
  "json",
  "rustls-tls",
  "multipart",
], default-features = false }
