//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "users"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: Uuid,
    pub username: Option<String>,
    pub created_at_utc: DateTimeWithTimeZone,
    pub updated_at_utc: DateTimeWithTimeZone,
    pub is_admin: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Username,
    CreatedAtUtc,
    UpdatedAtUtc,
    IsAdmin,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    OauthTokens,
    Sessions,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::Username => ColumnType::Text.def().null().unique(),
            Self::CreatedAtUtc => ColumnType::TimestampWithTimeZone.def(),
            Self::UpdatedAtUtc => ColumnType::TimestampWithTimeZone.def(),
            Self::IsAdmin => ColumnType::Boolean.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::OauthTokens => Entity::has_many(super::oauth_tokens::Entity).into(),
            Self::Sessions => Entity::has_many(super::sessions::Entity).into(),
        }
    }
}

impl Related<super::oauth_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OauthTokens.def()
    }
}

impl Related<super::sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sessions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
